version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/web/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bughunting_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2

  celery:
    build:
      context: .
      dockerfile: dockerfiles/celery/Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      dockerfile: dockerfiles/celery_beat/Dockerfile
    command: celery -A bughunting_dashboard beat -l info
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
